// Browser-safe column definitions for all report types
// This file must NOT import Node.js modules (pdfkit, exceljs, fs)

export const REPORT_COLUMNS: Record<string, { label: string; key: string }[]> = {
  registration: [
    { label: 'Date', key: 'registrationDate' }, { label: 'Campaign', key: 'campaign' },
    { label: 'Customer', key: 'customerName' }, { label: 'Mobile', key: 'customerMobile' },
    { label: 'Vehicle No.', key: 'vehicleNumber' }, { label: 'Vehicle Type', key: 'vehicleType' },
    { label: 'Fuel Type', key: 'fuelType' }, { label: 'Fuel Amt (₹)', key: 'fuelAmount' },
    { label: 'Bill No.', key: 'billNumber' }, { label: 'Status', key: 'status' },
    { label: 'Station', key: 'stationCode' }, { label: 'Territory', key: 'territory' },
  ],
  bill_upload: [
    { label: 'Upload Date', key: 'uploadDate' }, { label: 'Bill No.', key: 'billNumber' },
    { label: 'Fuel Amt (₹)', key: 'fuelAmount' }, { label: 'Format', key: 'fileFormat' },
    { label: 'OCR Bill No.', key: 'ocrBillNumber' }, { label: 'OCR Amount', key: 'ocrAmount' },
    { label: 'OCR Confidence', key: 'ocrConfidence' }, { label: 'Validation Status', key: 'validationStatus' },
    { label: 'Station', key: 'stationCode' }, { label: 'Reg. Status', key: 'registrationStatus' },
  ],
  bill_validation: [
    { label: 'Bill No.', key: 'billNumber' }, { label: 'Fuel Amt (₹)', key: 'fuelAmount' },
    { label: 'Validation Status', key: 'validationStatus' }, { label: 'OCR Confidence', key: 'ocrConfidence' },
    { label: 'Reviewer Notes', key: 'reviewerNotes' }, { label: 'Validated By', key: 'validatedBy' },
    { label: 'Validated At', key: 'validatedAt' }, { label: 'Station', key: 'stationCode' },
  ],
  territory_performance: [
    { label: 'Code', key: 'territoryCode' }, { label: 'Territory', key: 'territoryName' },
    { label: 'State', key: 'state' }, { label: 'Active Stations', key: 'activeStations' },
    { label: 'Total Stations', key: 'totalStations' }, { label: 'Total Regs', key: 'totalRegistrations' },
    { label: 'Valid Regs', key: 'validRegistrations' }, { label: 'Validation Rate', key: 'validationRate' },
    { label: 'Total Fuel (₹)', key: 'totalFuelAmount' },
  ],
  station_performance: [
    { label: 'Station Code', key: 'stationCode' }, { label: 'Station Name', key: 'stationName' },
    { label: 'City', key: 'city' }, { label: 'Territory', key: 'territory' },
    { label: 'DSM', key: 'dsmName' }, { label: 'Active', key: 'isActive' },
    { label: 'Total Regs', key: 'totalRegistrations' }, { label: 'Valid Regs', key: 'validRegistrations' },
    { label: 'Validation %', key: 'validationRate' }, { label: 'Fuel (₹)', key: 'totalFuelAmount' },
    { label: 'QR Scans', key: 'qrScans' },
  ],
  instant_reward: [
    { label: 'Issued At', key: 'issuedAt' }, { label: 'Coupon Code', key: 'couponCode' },
    { label: 'Reward', key: 'rewardTitle' }, { label: 'Type', key: 'rewardType' },
    { label: 'Value (₹)', key: 'rewardValue' }, { label: 'Status', key: 'status' },
    { label: 'Customer', key: 'customerName' }, { label: 'Mobile', key: 'customerMobile' },
    { label: 'Bill No.', key: 'billNumber' }, { label: 'Station', key: 'stationCode' },
  ],
  draw: [
    { label: 'Draw Name', key: 'drawName' }, { label: 'Type', key: 'drawType' },
    { label: 'Campaign', key: 'campaign' }, { label: 'Scheduled Date', key: 'scheduledDate' },
    { label: 'Status', key: 'status' }, { label: 'Winner Count', key: 'winnerCount' },
    { label: 'Eligible Entries', key: 'totalEligibleEntries' }, { label: 'Winners Selected', key: 'winnersSelected' },
    { label: 'Executed At', key: 'executedAt' }, { label: 'Executed By', key: 'executedBy' },
    { label: 'Execution Hash', key: 'executionHash' },
  ],
  winner: [
    { label: 'Draw', key: 'drawName' }, { label: 'Draw Type', key: 'drawType' },
    { label: 'Draw Date', key: 'drawDate' }, { label: 'Customer', key: 'customerName' },
    { label: 'Mobile', key: 'customerMobile' }, { label: 'Vehicle No.', key: 'vehicleNumber' },
    { label: 'Prize', key: 'prizeName' }, { label: 'Prize Value (₹)', key: 'prizeValue' },
    { label: 'Verification Status', key: 'verificationStatus' }, { label: 'Verified At', key: 'verifiedAt' },
    { label: 'Station', key: 'stationCode' }, { label: 'Dispatch Status', key: 'dispatchStatus' },
    { label: 'Tracking No.', key: 'trackingNumber' }, { label: 'Delivered At', key: 'deliveredAt' },
  ],
  prize_distribution: [
    { label: 'Category', key: 'category' }, { label: 'Campaign', key: 'campaign' },
    { label: 'Name', key: 'name' }, { label: 'SKU', key: 'sku' }, { label: 'Type', key: 'prizeType' },
    { label: 'Total Stock', key: 'totalStock' }, { label: 'Available', key: 'availableStock' },
    { label: 'Allocated', key: 'allocated' }, { label: 'Unit Value (₹)', key: 'unitValue' },
    { label: 'Total Value (₹)', key: 'totalValue' },
  ],
  dispatch: [
    { label: 'Prize', key: 'prizeName' }, { label: 'Prize Value (₹)', key: 'prizeValue' },
    { label: 'Receiver', key: 'receiverName' }, { label: 'Mobile', key: 'receiverMobile' },
    { label: 'Nodal Point', key: 'nodalPoint' }, { label: 'Status', key: 'dispatchStatus' },
    { label: 'Tracking No.', key: 'trackingNumber' }, { label: 'Dispatched At', key: 'dispatchedAt' },
    { label: 'Delivered At', key: 'deliveredAt' }, { label: 'Photo Proof', key: 'hasPhotoProof' },
    { label: 'Signature', key: 'hasSignatureProof' }, { label: 'Station', key: 'stationCode' },
  ],
  dsm_performance: [
    { label: 'DSM Code', key: 'dsmCode' }, { label: 'DSM Name', key: 'dsmName' },
    { label: 'Territory', key: 'territory' }, { label: 'Stations', key: 'stationCount' },
    { label: 'Total Regs', key: 'totalRegistrations' }, { label: 'Valid Regs', key: 'validRegistrations' },
    { label: 'Validation %', key: 'validationRate' }, { label: 'Fuel (₹)', key: 'totalFuelAmount' },
    { label: 'QR Scans', key: 'qrScans' },
  ],
  audit: [
    { label: 'Timestamp', key: 'timestamp' }, { label: 'Actor', key: 'actorName' },
    { label: 'Email', key: 'actorEmail' }, { label: 'Role', key: 'actorRole' },
    { label: 'Action', key: 'action' }, { label: 'Entity Type', key: 'entityType' },
    { label: 'Entity ID', key: 'entityId' }, { label: 'IP Address', key: 'ipAddress' },
    { label: 'Changes', key: 'changes' },
  ],
};
